
/// Returns a brief description for a given WebAssembly instruction mnemonic.
pub fn get_instruction_help(mnemonic: &str) -> Option<&'static str> {
    match mnemonic {
        // Control Flow
        "unreachable" => Some("Traps immediately. Execution is aborted."),
        "nop" => Some("No operation. Does nothing."),
        "block" => Some("Begins a block sequence. Pushes a label onto the control stack."),
        "loop" => Some("Begins a loop block. Pushes a label onto the control stack. 'br' to this label jumps to the loop start."),
        "if" => Some("Pops an i32 condition. If non-zero, enters the block; otherwise, jumps to 'else' or 'end'."),
        "else" => Some("Marks the start of the 'else' branch in an 'if' block."),
        "end" => Some("Ends a block, loop, or if structure."),
        "br" => Some("Unconditional branch. Jumps to a label (relative depth), unwinding the stack."),
        "br_if" => Some("Pops an i32 condition. If non-zero, branches to the label; otherwise, continues."),
        "br_table" => Some("Pops an i32 index. Branches to the label at that index in the table, or the default label."),
        "return" => Some("Returns from the current function, popping results (if any) from the stack."),
        "call" => Some("Calls a function. Pops arguments from the stack and pushes return values."),
        "call_indirect" => Some("Pops an i32 table index. Calls the function at that index in the table."),
        "drop" => Some("Pops a value from the stack and discards it."),
        "select" => Some("Pops v1, v2, and cond (i32). If cond != 0, pushes v1; else pushes v2."),

        // Variable Access
        "local.get" => Some("Pushes the value of a local variable onto the stack."),
        "local.set" => Some("Pops a value from the stack and stores it in a local variable."),
        "local.tee" => Some("Pops a value, stores it in a local variable, and pushes it back onto the stack."),
        "global.get" => Some("Pushes the value of a global variable onto the stack."),
        "global.set" => Some("Pops a value from the stack and stores it in a global variable."),

        // Memory
        "i32.load" => Some("Pops an i32 address. Loads an i32 from memory and pushes it."),
        "i64.load" => Some("Pops an i32 address. Loads an i64 from memory and pushes it."),
        "f32.load" => Some("Pops an i32 address. Loads an f32 from memory and pushes it."),
        "f64.load" => Some("Pops an i32 address. Loads an f64 from memory and pushes it."),
        "i32.load8_s" => Some("Pops an i32 address. Loads 8 bits, sign-extends to i32, and pushes it."),
        "i32.load8_u" => Some("Pops an i32 address. Loads 8 bits, zero-extends to i32, and pushes it."),
        "i32.load16_s" => Some("Pops an i32 address. Loads 16 bits, sign-extends to i32, and pushes it."),
        "i32.load16_u" => Some("Pops an i32 address. Loads 16 bits, zero-extends to i32, and pushes it."),
        "i64.load8_s" => Some("Pops an i32 address. Loads 8 bits, sign-extends to i64, and pushes it."),
        "i64.load8_u" => Some("Pops an i32 address. Loads 8 bits, zero-extends to i64, and pushes it."),
        "i64.load16_s" => Some("Pops an i32 address. Loads 16 bits, sign-extends to i64, and pushes it."),
        "i64.load16_u" => Some("Pops an i32 address. Loads 16 bits, zero-extends to i64, and pushes it."),
        "i64.load32_s" => Some("Pops an i32 address. Loads 32 bits, sign-extends to i64, and pushes it."),
        "i64.load32_u" => Some("Pops an i32 address. Loads 32 bits, zero-extends to i64, and pushes it."),
        "i32.store" => Some("Pops an i32 value and i32 address. Stores the value to memory."),
        "i64.store" => Some("Pops an i64 value and i32 address. Stores the value to memory."),
        "f32.store" => Some("Pops an f32 value and i32 address. Stores the value to memory."),
        "f64.store" => Some("Pops an f64 value and i32 address. Stores the value to memory."),
        "i32.store8" => Some("Pops an i32 value and i32 address. Stores the low 8 bits to memory."),
        "i32.store16" => Some("Pops an i32 value and i32 address. Stores the low 16 bits to memory."),
        "i64.store8" => Some("Pops an i64 value and i32 address. Stores the low 8 bits to memory."),
        "i64.store16" => Some("Pops an i64 value and i32 address. Stores the low 16 bits to memory."),
        "i64.store32" => Some("Pops an i64 value and i32 address. Stores the low 32 bits to memory."),
        "memory.size" => Some("Pushes the current size of memory (in pages)."),
        "memory.grow" => Some("Pops a number of pages (delta). Grows memory. Pushes old size or -1 on failure."),

        // Constants
        "i32.const" => Some("Pushes a constant i32 value onto the stack."),
        "i64.const" => Some("Pushes a constant i64 value onto the stack."),
        "f32.const" => Some("Pushes a constant f32 value onto the stack."),
        "f64.const" => Some("Pushes a constant f64 value onto the stack."),

        // Comparison
        "i32.eqz" => Some("Pops an i32. Pushes 1 if zero, 0 otherwise."),
        "i32.eq" => Some("Pops two i32 values. Pushes 1 if equal, 0 otherwise."),
        "i32.ne" => Some("Pops two i32 values. Pushes 1 if not equal, 0 otherwise."),
        "i32.lt_s" => Some("Pops two i32 values. Pushes 1 if first < second (signed), 0 otherwise."),
        "i32.lt_u" => Some("Pops two i32 values. Pushes 1 if first < second (unsigned), 0 otherwise."),
        "i32.gt_s" => Some("Pops two i32 values. Pushes 1 if first > second (signed), 0 otherwise."),
        "i32.gt_u" => Some("Pops two i32 values. Pushes 1 if first > second (unsigned), 0 otherwise."),
        "i32.le_s" => Some("Pops two i32 values. Pushes 1 if first <= second (signed), 0 otherwise."),
        "i32.le_u" => Some("Pops two i32 values. Pushes 1 if first <= second (unsigned), 0 otherwise."),
        "i32.ge_s" => Some("Pops two i32 values. Pushes 1 if first >= second (signed), 0 otherwise."),
        "i32.ge_u" => Some("Pops two i32 values. Pushes 1 if first >= second (unsigned), 0 otherwise."),

        "i64.eqz" => Some("Pops an i64. Pushes 1 if zero, 0 otherwise."),
        "i64.eq" => Some("Pops two i64 values. Pushes 1 if equal, 0 otherwise."),
        "i64.ne" => Some("Pops two i64 values. Pushes 1 if not equal, 0 otherwise."),
        "i64.lt_s" => Some("Pops two i64 values. Pushes 1 if first < second (signed), 0 otherwise."),
        "i64.lt_u" => Some("Pops two i64 values. Pushes 1 if first < second (unsigned), 0 otherwise."),
        "i64.gt_s" => Some("Pops two i64 values. Pushes 1 if first > second (signed), 0 otherwise."),
        "i64.gt_u" => Some("Pops two i64 values. Pushes 1 if first > second (unsigned), 0 otherwise."),
        "i64.le_s" => Some("Pops two i64 values. Pushes 1 if first <= second (signed), 0 otherwise."),
        "i64.le_u" => Some("Pops two i64 values. Pushes 1 if first <= second (unsigned), 0 otherwise."),
        "i64.ge_s" => Some("Pops two i64 values. Pushes 1 if first >= second (signed), 0 otherwise."),
        "i64.ge_u" => Some("Pops two i64 values. Pushes 1 if first >= second (unsigned), 0 otherwise."),

        "f32.eq" => Some("Pops two f32 values. Pushes 1 if equal, 0 otherwise."),
        "f32.ne" => Some("Pops two f32 values. Pushes 1 if not equal, 0 otherwise."),
        "f32.lt" => Some("Pops two f32 values. Pushes 1 if first < second, 0 otherwise."),
        "f32.gt" => Some("Pops two f32 values. Pushes 1 if first > second, 0 otherwise."),
        "f32.le" => Some("Pops two f32 values. Pushes 1 if first <= second, 0 otherwise."),
        "f32.ge" => Some("Pops two f32 values. Pushes 1 if first >= second, 0 otherwise."),

        "f64.eq" => Some("Pops two f64 values. Pushes 1 if equal, 0 otherwise."),
        "f64.ne" => Some("Pops two f64 values. Pushes 1 if not equal, 0 otherwise."),
        "f64.lt" => Some("Pops two f64 values. Pushes 1 if first < second, 0 otherwise."),
        "f64.gt" => Some("Pops two f64 values. Pushes 1 if first > second, 0 otherwise."),
        "f64.le" => Some("Pops two f64 values. Pushes 1 if first <= second, 0 otherwise."),
        "f64.ge" => Some("Pops two f64 values. Pushes 1 if first >= second, 0 otherwise."),

        // Numeric
        "i32.clz" => Some("Pops an i32. Pushes the count of leading zeros."),
        "i32.ctz" => Some("Pops an i32. Pushes the count of trailing zeros."),
        "i32.popcnt" => Some("Pops an i32. Pushes the count of set bits."),
        "i32.add" => Some("Pops two i32 values. Pushes their sum."),
        "i32.sub" => Some("Pops two i32 values. Pushes the result of first - second."),
        "i32.mul" => Some("Pops two i32 values. Pushes their product."),
        "i32.div_s" => Some("Pops two i32 values. Pushes the result of first / second (signed)."),
        "i32.div_u" => Some("Pops two i32 values. Pushes the result of first / second (unsigned)."),
        "i32.rem_s" => Some("Pops two i32 values. Pushes the remainder of first / second (signed)."),
        "i32.rem_u" => Some("Pops two i32 values. Pushes the remainder of first / second (unsigned)."),
        "i32.and" => Some("Pops two i32 values. Pushes their bitwise AND."),
        "i32.or" => Some("Pops two i32 values. Pushes their bitwise OR."),
        "i32.xor" => Some("Pops two i32 values. Pushes their bitwise XOR."),
        "i32.shl" => Some("Pops value and shift amount (i32). Pushes value << amount."),
        "i32.shr_s" => Some("Pops value and shift amount (i32). Pushes value >> amount (arithmetic)."),
        "i32.shr_u" => Some("Pops value and shift amount (i32). Pushes value >> amount (logical)."),
        "i32.rotl" => Some("Pops value and rotate amount (i32). Pushes value rotated left."),
        "i32.rotr" => Some("Pops value and rotate amount (i32). Pushes value rotated right."),

        "i64.clz" => Some("Pops an i64. Pushes the count of leading zeros."),
        "i64.ctz" => Some("Pops an i64. Pushes the count of trailing zeros."),
        "i64.popcnt" => Some("Pops an i64. Pushes the count of set bits."),
        "i64.add" => Some("Pops two i64 values. Pushes their sum."),
        "i64.sub" => Some("Pops two i64 values. Pushes the result of first - second."),
        "i64.mul" => Some("Pops two i64 values. Pushes their product."),
        "i64.div_s" => Some("Pops two i64 values. Pushes the result of first / second (signed)."),
        "i64.div_u" => Some("Pops two i64 values. Pushes the result of first / second (unsigned)."),
        "i64.rem_s" => Some("Pops two i64 values. Pushes the remainder of first / second (signed)."),
        "i64.rem_u" => Some("Pops two i64 values. Pushes the remainder of first / second (unsigned)."),
        "i64.and" => Some("Pops two i64 values. Pushes their bitwise AND."),
        "i64.or" => Some("Pops two i64 values. Pushes their bitwise OR."),
        "i64.xor" => Some("Pops two i64 values. Pushes their bitwise XOR."),
        "i64.shl" => Some("Pops value and shift amount (i64). Pushes value << amount."),
        "i64.shr_s" => Some("Pops value and shift amount (i64). Pushes value >> amount (arithmetic)."),
        "i64.shr_u" => Some("Pops value and shift amount (i64). Pushes value >> amount (logical)."),
        "i64.rotl" => Some("Pops value and rotate amount (i64). Pushes value rotated left."),
        "i64.rotr" => Some("Pops value and rotate amount (i64). Pushes value rotated right."),

        "f32.abs" => Some("Pops an f32. Pushes its absolute value."),
        "f32.neg" => Some("Pops an f32. Pushes its negation."),
        "f32.ceil" => Some("Pops an f32. Pushes its ceiling."),
        "f32.floor" => Some("Pops an f32. Pushes its floor."),
        "f32.trunc" => Some("Pops an f32. Pushes its integral part (truncated)."),
        "f32.nearest" => Some("Pops an f32. Pushes the nearest integer."),
        "f32.sqrt" => Some("Pops an f32. Pushes its square root."),
        "f32.add" => Some("Pops two f32 values. Pushes their sum."),
        "f32.sub" => Some("Pops two f32 values. Pushes the result of first - second."),
        "f32.mul" => Some("Pops two f32 values. Pushes their product."),
        "f32.div" => Some("Pops two f32 values. Pushes the result of first / second."),
        "f32.min" => Some("Pops two f32 values. Pushes the minimum."),
        "f32.max" => Some("Pops two f32 values. Pushes the maximum."),
        "f32.copysign" => Some("Pops two f32 values. Pushes the first with the sign of the second."),

        "f64.abs" => Some("Pops an f64. Pushes its absolute value."),
        "f64.neg" => Some("Pops an f64. Pushes its negation."),
        "f64.ceil" => Some("Pops an f64. Pushes its ceiling."),
        "f64.floor" => Some("Pops an f64. Pushes its floor."),
        "f64.trunc" => Some("Pops an f64. Pushes its integral part (truncated)."),
        "f64.nearest" => Some("Pops an f64. Pushes the nearest integer."),
        "f64.sqrt" => Some("Pops an f64. Pushes its square root."),
        "f64.add" => Some("Pops two f64 values. Pushes their sum."),
        "f64.sub" => Some("Pops two f64 values. Pushes the result of first - second."),
        "f64.mul" => Some("Pops two f64 values. Pushes their product."),
        "f64.div" => Some("Pops two f64 values. Pushes the result of first / second."),
        "f64.min" => Some("Pops two f64 values. Pushes the minimum."),
        "f64.max" => Some("Pops two f64 values. Pushes the maximum."),
        "f64.copysign" => Some("Pops two f64 values. Pushes the first with the sign of the second."),

        // Conversions
        "i32.wrap_i64" => Some("Pops an i64. Pushes it wrapped to i32 (modulo 2^32)."),
        "i32.trunc_f32_s" => Some("Pops an f32. Pushes it truncated to i32 (signed)."),
        "i32.trunc_f32_u" => Some("Pops an f32. Pushes it truncated to i32 (unsigned)."),
        "i32.trunc_f64_s" => Some("Pops an f64. Pushes it truncated to i32 (signed)."),
        "i32.trunc_f64_u" => Some("Pops an f64. Pushes it truncated to i32 (unsigned)."),
        "i64.extend_i32_s" => Some("Pops an i32. Pushes it extended to i64 (signed)."),
        "i64.extend_i32_u" => Some("Pops an i32. Pushes it extended to i64 (unsigned)."),
        "i64.trunc_f32_s" => Some("Pops an f32. Pushes it truncated to i64 (signed)."),
        "i64.trunc_f32_u" => Some("Pops an f32. Pushes it truncated to i64 (unsigned)."),
        "i64.trunc_f64_s" => Some("Pops an f64. Pushes it truncated to i64 (signed)."),
        "i64.trunc_f64_u" => Some("Pops an f64. Pushes it truncated to i64 (unsigned)."),
        "f32.convert_i32_s" => Some("Pops an i32. Pushes it converted to f32 (signed)."),
        "f32.convert_i32_u" => Some("Pops an i32. Pushes it converted to f32 (unsigned)."),
        "f32.convert_i64_s" => Some("Pops an i64. Pushes it converted to f32 (signed)."),
        "f32.convert_i64_u" => Some("Pops an i64. Pushes it converted to f32 (unsigned)."),
        "f32.demote_f64" => Some("Pops an f64. Pushes it demoted to f32."),
        "f64.convert_i32_s" => Some("Pops an i32. Pushes it converted to f64 (signed)."),
        "f64.convert_i32_u" => Some("Pops an i32. Pushes it converted to f64 (unsigned)."),
        "f64.convert_i64_s" => Some("Pops an i64. Pushes it converted to f64 (signed)."),
        "f64.convert_i64_u" => Some("Pops an i64. Pushes it converted to f64 (unsigned)."),
        "f64.promote_f32" => Some("Pops an f32. Pushes it promoted to f64."),
        "i32.reinterpret_f32" => Some("Pops an f32. Pushes its bits reinterpreted as i32."),
        "i64.reinterpret_f64" => Some("Pops an f64. Pushes its bits reinterpreted as i64."),
        "f32.reinterpret_i32" => Some("Pops an i32. Pushes its bits reinterpreted as f32."),
        "f64.reinterpret_i64" => Some("Pops an i64. Pushes its bits reinterpreted as f64."),

        // Extended integer operations (sign-extension)
        "i32.extend8_s" => Some("Pops an i32. Sign-extends from 8 bits to 32 bits."),
        "i32.extend16_s" => Some("Pops an i32. Sign-extends from 16 bits to 32 bits."),
        "i64.extend8_s" => Some("Pops an i64. Sign-extends from 8 bits to 64 bits."),
        "i64.extend16_s" => Some("Pops an i64. Sign-extends from 16 bits to 64 bits."),
        "i64.extend32_s" => Some("Pops an i64. Sign-extends from 32 bits to 64 bits."),

        // Saturating truncation (nontrapping)
        "i32.trunc_sat_f32_s" => Some("Pops an f32. Truncates to i32 (signed), saturating on overflow."),
        "i32.trunc_sat_f32_u" => Some("Pops an f32. Truncates to i32 (unsigned), saturating on overflow."),
        "i32.trunc_sat_f64_s" => Some("Pops an f64. Truncates to i32 (signed), saturating on overflow."),
        "i32.trunc_sat_f64_u" => Some("Pops an f64. Truncates to i32 (unsigned), saturating on overflow."),
        "i64.trunc_sat_f32_s" => Some("Pops an f32. Truncates to i64 (signed), saturating on overflow."),
        "i64.trunc_sat_f32_u" => Some("Pops an f32. Truncates to i64 (unsigned), saturating on overflow."),
        "i64.trunc_sat_f64_s" => Some("Pops an f64. Truncates to i64 (signed), saturating on overflow."),
        "i64.trunc_sat_f64_u" => Some("Pops an f64. Truncates to i64 (unsigned), saturating on overflow."),

        // Reference types
        "ref.null" => Some("Pushes a null reference of the specified type."),
        "ref.is_null" => Some("Pops a reference. Pushes 1 if null, 0 otherwise."),
        "ref.func" => Some("Creates a reference to the specified function."),

        // Table operations
        "table.get" => Some("Gets an element from a table at the given index."),
        "table.set" => Some("Sets an element in a table at the given index."),
        "table.size" => Some("Pushes the current size of a table."),
        "table.grow" => Some("Grows a table by a given number of elements."),
        "table.fill" => Some("Fills a table range with a value."),
        "table.copy" => Some("Copies elements between tables."),
        "table.init" => Some("Copies elements from a passive element segment to a table."),

        // Bulk memory operations
        "memory.copy" => Some("Copies bytes within memory."),
        "memory.fill" => Some("Fills a memory region with a byte value."),
        "memory.init" => Some("Copies bytes from a passive data segment to memory."),
        "data.drop" => Some("Discards a passive data segment."),
        "elem.drop" => Some("Discards a passive element segment."),

        // Catch-all for unknown instructions
        _ => Some("Unknown WebAssembly instruction. See spec for details."),
    }
}
